server:
  port: 80
 

spring:
  thymeleaf:
    cache: false
    
  mvc:
     favicon:
      enabled: true
      
  datasource:
    url: jdbc:mysql://localhost:3306/arachne_db?useSSL=false
    username: ksr_arachne_dev
    password: arachne_password